image_path = r"C:\Users\tannu\Desktop\python task_files\IMG_8820.jpg"
image = Image.open(image_path)
blurred_image = image.filter(ImageFilter.BLUR)
blurred_image.show() 
contour_image = image.filter(ImageFilter.CONTOUR)
contour_image.show()  
detail_image = image.filter(ImageFilter.DETAIL)
detail_image.show()  
sharpened_image = image.filter(ImageFilter.SHARPEN)
sharpened_image.show() 
edge_enhanced_image = image.filter(ImageFilter.EDGE_ENHANCE)
edge_enhanced_image.show()  
embossed_image = image.filter(ImageFilter.EMBOSS)
embossed_image.show()  
enhancer = ImageEnhance.Brightness(image)
bright_image = enhancer.enhance(1.5)  
bright_image.show()  

enhancer = ImageEnhance.Contrast(image)
contrast_image = enhancer.enhance(2.0)  
contrast_image.show()  
enhancer = ImageEnhance.Color(image)
color_image = enhancer.enhance(1.5)  
color_image.show()  
gray_image = image.convert("L")
gray_image.show()  
blurred_image.save("blurred_image.jpg")
contour_image.save("contour_image.jpg")
detail_image.save("detail_image.jpg")
sharpened_image.save("sharpened_image.jpg")
edge_enhanced_image.save("edge_enhanced_image.jpg")
embossed_image.save("embossed_image.jpg")
bright_image.save("bright_image.jpg")
contrast_image.save("contrast_image.jpg")
color_image.save("color_image.jpg")
gray_image.save("gray_image.jpg")